Revert "arm: process.c: Define arm_pm_idle"
This reverts commit 2e9491798cfd7ef60a1d9abe7773a4e175fdb67b.

The hack to define arm_pm_idle this way breaks upstream/multiplatform
builds at link time:

arch/arm/kernel/built-in.o: In function `.LANCHOR0':
:(.data+0x58): undefined reference to `arch_idle'
make: *** [vmlinux] Error 1

We will move setting arch_pm_idle into drivers/power/qcom instead

Signed-off-by: Kumar Gala <galak@codeaurora.org>
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>